### ISSUE TITLE
Support "/" in tag prefix to support Go multimodule repositories

### ISSUE THREAD

**Issue by orizerah** [chaaz/versio#13]
I can't seem to find a solid versioning solution to my multi-module go repository.
In Go, each tag of a sub-module in the repository has the format `{NAME}/v{SEMVER}`.
But currently, versio doesn't allow to put '/' in the tag_prefix.

Allow more characters (specifically '/') in the `tag_prefix` configuration key

I tried GitVersion, it both doesn't support this feature, and it's written in C#, so I prefer using versio.

**Comment by chaaz** [comment]
@orizerah, @tamirkiviti13, @slootzky, @naortalmor1, @ShiraCohen33 : The latest release 0.6.5 allows the "/" character in the "tag_prefix" property, and adds the "tag_prefix_separator" property for finer control over the full tag name. Let me know if this works for you!
