### ISSUE TITLE
Add support for custom commit message

### ISSUE THREAD

**Issue by robko23** [chaaz/versio#15]
It would be nice if I could set the commit message (or perhaps even author?)  for the version bump commit.

When I have automated pipeline, it triggers on commit and then triggers again after the version bump.
Preferably, this could be set through the config file and it would be optional.

**Comment by chaaz** [comment]
Hey, @robko23 ! Thanks for your contribution. I've accepted your PR with a few tweaks, but I think the functionality that you intended should be working, and will be included in the next release.
