### ISSUE TITLE
Changelog customization

### ISSUE THREAD

**Issue by alexmg** [chaaz/versio#6]
I have been evaluating this tool and I am impressed with the feature set, particularly the way it handles the versioning of multiple projects within a monorepo. This is not something that the other tools I have looked at are attempting to address.

With the versioning issues being solved with Versio I looked at the changelog generation feature and while it does what is expected there does not seem to be a mechanism for customization of the output. I would like to generate release notes/changelog in Markdown format, ideally with the changes grouped based on the scope in the conventional commits along with hyperlinks to the individual commits.

The changelog appears to be generated using a liquid template that is embedded in the binary. I have seen a couple of approaches to changelog generation including various levels of templatization to writing out the conventional commit details in JSON format. I do like the later approach as the data can be used with any templating language and converted into any format.

It would be amazing to see something similar in Versio as it is difficult to utilize such a feature from another tool because they are not monorepo aware. Given two known tags in the repository the other tools would pick up commits that are not relevant for the individual project the changelog is being generated for.

Thanks for sharing this amazing project with the community.

**Comment by chaaz** [comment]
Thanks, @alexmg ! I'm glad you're enjoying using Versio. I certainly have been playing around with various changelog options--I release that the default template is not for everyone. My first thought is that I could allow users to provide their own liquid template, via a command-line option like `--log-template` or something. Liquid is similar to the standard handlebars / mustache / etc. style templates, so I think it wouldn't be too much for users to learn.

I'm also intrigued by your idea of "writing out the conventinal commit details in JSON format". Are you thinking of something like what `versio plan` currently outputs, but in a more structured (i.e. JSON) format? I think that could be done pretty easily.

**Comment by alexmg** [comment]
I am familiar with Liquid templates and think that would be a good templating language choice. When it comes to templates, I think it would help if there was a default template available that can be used as a starting point and tweaked. That would be particularly helpful if the desired changes were only minor in nature and would prevent the need to start from nothing. The default templates could be exported using a command-line option in an equivalent manner to what is often done for initializing a default configuration file.

The idea for the JSON export would be to export similar information as the `plan` command but in JSON format so that it could unlock some other scenarios like:

- Using a different templating language if a user is already experienced in another language or simply has a strong preference over Liquid. They can feed the JSON data into their own template and take complete control over the templating process.
- Provide a way for the data to be manipulated prior to templating so if a user wants a different structure or grouping to work with in their own template, they can adjust the data themselves.
- Allow the data that has now been extracted from Git and parsed into conventional commit format to be imported into a database where it could be analyzed to get insights into the types of changes being made across different versions etc.

The JSON export combined with an example template and instruction on applying it would cover the changelog customization scenario and provide some additional opportunities at the same time.

**Comment by chaaz** [comment]
@alexmg ! It has been a while: sorry for the long response--Real Life intervened, and then I spent way too much time futilely banging my head against Windows build systems.

Anyway, after that I managed to make some significant additions to Versio's changelog functionality in the [0.6.0 release](https://github.com/chaaz/versio/releases/tag/v0.6.0). Please take a look, at let me know what you think.

For your use cases specifically, we've got:
- The ability to output the default HTML or JSON template with `versio template`
- The ability to set your own template file in the configuration--you can use a file or http location
- You can also just output a project's release plan using a template (including the builtin JSON template) instead of plain text.

Let me know what you think!

**Comment by alexmg** [comment]
This sounds very cool @chaaz. I am keen to test this out.

I grabbed the latest Windows binary (`v0.6.0`) but when running in Windows Terminal didn't see any output. I then tried running under `cmd` directly and got the two errors below in one message box and then another. Windows Terminal was obviously suppressing the message boxes.

```
---------------------------
versio__x86_64-pc-win32.exe - System Error
---------------------------
The code execution cannot proceed because libgpgme-11.dll was not found. Reinstalling the program may fix this problem. 
```

```
---------------------------
versio__x86_64-pc-win32.exe - System Error
---------------------------
The code execution cannot proceed because libgpg-error-0.dll was not found. Reinstalling the program may fix this problem. 
```

I also tried the previous version (`v0.5.4`) and this was reported as `Trojan:Win32/Sabsik.TE.A!ml` when downloaded. A false positive no doubt but thought I would mention it.

**Comment by chaaz** [comment]
Yeah, Windows GPG dependencies proved to be quite vexing. The 0.6.0 binary is what you want, but I think you may need to install the GnuPG / GpgME package, which you can download from [here](https://gnupg.org/ftp/gcrypt/binary/gnupg-w32-2.3.1_20210420.exe), and make sure that the package's `bin` directory shows up early in your PATH. See [Dependencies](https://github.com/chaaz/versio/blob/main/docs/dependencies.md#windows) for more info.

**Comment by alexmg** [comment]
I installed the GPG dependencies with `choco` but had not restarted the terminal. Got it running now and will check out the new features.

**Comment by chaaz** [comment]
Just FYI, you may want to upgrade to [0.6.1](https://github.com/chaaz/versio/releases/tag/v0.6.1), which fixes a bug that you might encounter during release.
